# Theoretical Questions

# 1)  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy (Numerical Python) provides an efficient framework for handling large arrays and matrices of numeric data, along with a large collection of high-level mathematical functions to operate on these arrays. Key advantages include:

Performance: NumPy is implemented in C, making its operations faster than standard Python lists for numerical computations.
Memory Efficiency: Arrays in NumPy use much less memory than Python lists due to the fixed type and compact memory layout.
Vectorized Operations: NumPy allows element-wise operations, eliminating the need for loops.
Interoperability: It integrates seamlessly with libraries like SciPy, Matplotlib, and Pandas, making it a cornerstone of the scientific Python ecosystem.

# 2) Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

np.mean(): Calculates the arithmetic mean of elements along a given axis or for the entire array. It gives equal weight to all elements.

np.average(): Also calculates the mean, but allows specifying weights to elements via the weights parameter.

You would use:

np.mean() for a simple mean calculation when all elements have the same significance.
np.average() when you want a weighted mean, where some elements contribute more to the final average than others.

# 3) Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

1D Array: You can reverse using slicing [::-1].

In [ ]:
arr = np.array([1, 2, 3, 4])
reversed_arr = arr[::-1]

2D Array: You can reverse rows or columns using np.flip() or axis-specific slicing.

In [13]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = np.flip(arr_2d, axis=0)  
reversed_columns = np.flip(arr_2d, axis=1)  

# 4) How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

 can determine the data type of a NumPy array using the dtype attribute.

In [14]:
arr = np.array([1, 2, 3])
print(arr.dtype)  

int32


Importance of data types:

Memory Management: Smaller data types (e.g., int8 vs int64) use less memory, making computations more memory-efficient.
Performance: Using the appropriate data type ensures faster computations as NumPy is optimized for fixed-type arrays.

# 5) Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarray stands for N-dimensional array. Key features:

Homogeneous data: All elements are of the same data type.
Efficient memory layout: Continuous memory allocation improves access speed.
Vectorized operations: Supports element-wise operations without loops.
Dimension and shape: Arrays can be multi-dimensional (1D, 2D, 3D, etc.).
Differences from Python lists:

Lists are heterogeneous, while NumPy arrays are homogeneous.
Lists are slower due to their flexibility and dynamic typing, whereas ndarray is optimized for numerical computations.

# 6) Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Speed: NumPy arrays are implemented in C, providing faster element access and mathematical operations.
Vectorization: NumPy supports operations over entire arrays without the need for explicit loops, leveraging CPU-level optimizations.
Memory Efficiency: Python lists store references to objects, which adds overhead. NumPy arrays store data directly in contiguous blocks of memory, reducing the overhead and improving memory locality.

# 7) 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

vstack(): Vertically stacks arrays (along rows).

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b)) 

array([[1, 2, 3],
       [4, 5, 6]])

hstack(): Horizontally stacks arrays (along columns).

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.hstack((a, b)) 

array([1, 2, 3, 4, 5, 6])

# 8) Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

fliplr(): Flips an array along its left-right axis (horizontally).

In [17]:
arr = np.array([[1, 2], [3, 4]])
np.fliplr(arr)  

array([[2, 1],
       [4, 3]])

flipud(): Flips an array along its up-down axis (vertically).

In [18]:
arr = np.array([[1, 2], [3, 4]])
np.flipud(arr)  

array([[3, 4],
       [1, 2]])

# 9) Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method divides an array into multiple sub-arrays. If the array cannot be split evenly, it creates sub-arrays with differing sizes, distributing the remainder elements as evenly as possible.

In [19]:
arr = np.array([1, 2, 3, 4, 5])
np.array_split(arr, 3) 

[array([1, 2]), array([3, 4]), array([5])]

# 10)  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization: The process of applying operations element-wise across entire arrays without explicit loops, making operations faster by leveraging low-level CPU instructions.

Example: arr * 2 multiplies every element by 2 without needing a loop.

Broadcasting: Enables operations on arrays of different shapes by automatically expanding smaller arrays to match the larger array’s shape.

In [20]:
arr = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
arr + arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Practical Questions

# 1) Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [22]:
import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))
print(arr)
transposed_arr = arr.T
print(transposed_arr)

[[ 4 27 54]
 [10 94 63]
 [42  5 67]]
[[ 4 10 42]
 [27 94  5]
 [54 63 67]]


# 2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [23]:
arr = np.arange(10)
reshaped_2x5 = arr.reshape(2, 5)
reshaped_5x2 = arr.reshape(5, 2)

# 3)Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [24]:
arr = np.random.rand(4, 4)
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

# 4) Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [25]:
arr = np.arange(10, 61, 5)

# 5) Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [26]:
arr = np.array(['python', 'numpy', 'pandas'])
uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)

# 6) Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
arr = np.array(['python', 'numpy', 'pandas'])
spaced = np.char.join(' ', arr)

# 7) Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array